#:schema node_modules/wrangler/config-schema.json
name = "discord-days-since-incident"
main = "src/index.ts"
compatibility_date = "2024-07-22"

[[kv_namespaces]]
binding = "GUILD_INCIDENTS"
id = "aa32847a1432461eb2f51ecad15ff478"